/**
 * jquery.json
 * xuhu added 20150427
 */
jQuery.extend({toJSON:function(e){var t=typeof e;if("object"==t){if(Array==e.constructor)t="array";else if(RegExp==e.constructor)t="regexp";else t="object"}switch(t){case"undefined":case"unknown":return;break;case"function":case"boolean":case"regexp":return e.toString();break;case"number":return isFinite(e)?e.toString():"null";break;case"string":return'"'+e.replace(/(\\|\")/g,"\\$1").replace(/\n|\r|\t/g,function(){var e=arguments[0];return e=="\n"?"\\n":e=="\r"?"\\r":e=="	"?"\\t":""})+'"';break;case"object":if(e===null)return"null";var n=[];for(var r in e){var i=jQuery.toJSON(e[r]);if(i!==undefined)n.push(jQuery.toJSON(r)+":"+i)}return"{"+n.join(",")+"}";break;case"array":var n=[];for(var s=0;s<e.length;s++){var i=jQuery.toJSON(e[s]);if(i!==undefined)n.push(i)}return"["+n.join(",")+"]";break}}})

/**
 * jquery.xml2json
 * xuhu added 20150427
 */
if(window.jQuery)(function(e){e.extend({xml2json:function(t,n){function r(t,s){if(!t)return null;var u="",a=null,f=null;var l=t.nodeType,c=i(t.localName||t.nodeName);var h=t.text||t.nodeValue||"";if(t.childNodes){if(t.childNodes.length>0){e.each(t.childNodes,function(e,t){var n=t.nodeType,s=i(t.localName||t.nodeName);var f=t.text||t.nodeValue||"";if(n==8){return}else if(n==3||n==4||!s){if(f.match(/^\s+$/)){return}u+=f.replace(/^\s+/,"").replace(/\s+$/,"")}else{a=a||{};if(a[s]){if(!a[s].length)a[s]=o(a[s]);a[s]=o(a[s]);a[s][a[s].length]=r(t,true);a[s].length=a[s].length}else{a[s]=r(t)}}})}}if(t.attributes){if(t.attributes.length>0){f={};a=a||{};e.each(t.attributes,function(e,t){var n=i(t.name),r=t.value;f[n]=r;if(a[n]){a[cnn]=o(a[cnn]);a[n][a[n].length]=r;a[n].length=a[n].length}else{a[n]=r}})}}if(a){a=e.extend(u!=""?new String(u):{},a||{});u=a.text?(typeof a.text=="object"?a.text:[a.text||""]).concat([u]):u;if(u)a.text=u;u=""}var p=a||u;if(n){if(u)p={};u=p.text||u||"";if(u)p.text=u;if(!s)p=o(p)}return p}function s(e){var t=/^((-)?([0-9]+)(([\.\,]{0,1})([0-9]+))?$)/;return typeof e=="number"||t.test(String(e&&typeof e=="string"?jQuery.trim(e):""))}if(!t)return{};var i=function(e){return String(e||"").replace(/-/g,"_")};var o=function(t){if(!e.isArray(t))t=[t];t.length=t.length;return t};if(typeof t=="string")t=e.text2xml(t);if(!t.nodeType)return;if(t.nodeType==3||t.nodeType==4)return t.nodeValue;var u=t.nodeType==9?t.documentElement:t;var a=r(u,true);t=null;u=null;return a},text2xml:function(t){var n;try{var r=e.browser.msie?new ActiveXObject("Microsoft.XMLDOM"):new DOMParser;r.async=false}catch(i){throw new Error("XML Parser could not be instantiated")}try{if(e.browser.msie)n=r.loadXML(t)?r:false;else n=r.parseFromString(t,"text/xml")}catch(i){throw new Error("Error parsing XML string")}return n}})})(jQuery)

/**
 * image rotate
 * xuhu added 20150427
 */
jQuery.fn.rotate=function(e,t){var n=this.get(0);if(!t){n.angle=((n.angle==undefined?0:n.angle)+e)%360}else{n.angle=e}if(n.angle>=0){var r=Math.PI*n.angle/180}else{var r=Math.PI*(360+n.angle)/180}var i=Math.round(Math.cos(r)*1e3)/1e3;var s=Math.round(Math.sin(r)*1e3)/1e3;if(document.all&&!window.opera){var o=document.createElement("img");o.src=n.src;o.height=n.height;o.width=n.width;o.style.filter="progid:DXImageTransform.Microsoft.Matrix(M11="+i+",M12="+ -s+",M21="+s+",M22="+i+",SizingMethod='auto expand')"}else{var o=document.createElement("canvas");if(!n.oImage){o.oImage=new Image;o.oImage.src=n.src}else{o.oImage=n.oImage}o.style.width=o.width=Math.abs(i*o.oImage.width)+Math.abs(s*o.oImage.height);o.style.height=o.height=Math.abs(i*o.oImage.height)+Math.abs(s*o.oImage.width);var u=o.getContext("2d");u.save();if(r<=Math.PI/2){u.translate(s*o.oImage.height,0)}else if(r<=Math.PI){u.translate(o.width,-i*o.oImage.height)}else if(r<=1.5*Math.PI){u.translate(-i*o.oImage.width,o.height)}else{u.translate(0,-s*o.oImage.width)}u.rotate(r);u.drawImage(o.oImage,0,0,o.oImage.width,o.oImage.height);u.restore()}o.id=n.id;o.angle=n.angle;n.parentNode.replaceChild(o,n)};jQuery.fn.rotateRight=function(e){this.rotate(e==undefined?90:e)};jQuery.fn.rotateLeft=function(e){this.rotate(e==undefined?-90:-e)}